---
- name: Docker pull node 14.15.0 | add to Ansible Hosts
  hosts: localhost
  tasks:
    - name: Pull node
      docker_container:
        name: "node-ansible-base"
        image: "node:14.15.0-stretch"
        state: started
        ports:
          - "8080:3000"
#        command: tail -f /dev/null
    - name: Add Image with Node to Ansible Hosts
      add_host:
        name: "node-ansible-base"
        ansible_connection: docker
        ansible_ssh_user: root

- name: Configure Node Image for deploy Web server
  hosts: "node-ansible-base"
  gather_facts: false
  tasks:
#    - name: Install Python3
#      raw: apt update && apt upgrade -y && apt install python3 -y
    - name: Install Rsync
      apt:
        name: rsync
    - name: Copy webapp files to docker container
      synchronize:
        src: ./web-app/
        dest: /var/www
    - name: Check node is enabled
      service:
        name: node
        enabled: yes
    - name: Clean up Rcync
      raw: apt purge rsync -y
#    - name: Clean up Python 3 and Prerequisites
#      raw: apt purge python3 rsync -y

- name: Yarn install dependenses, build and start on container
  hosts: "node-ansible-base"
  tasks:
    - name: Doing Yarn install command
      command: yarn install
    - name: Doing Yarn build command
      command: yarn build
    - name: Doing Yarn start command
      command: yarn start


#- name: Snapshot base image to create newly configured Image
#  hosts: localhost
#  tasks:
#    - name: Commit Docker image
#      command: docker commit "nginx-ansible-base" "nginx-ansible-build-demo"
#
#- name: Clean Up Docker Containers
#  hosts: localhost
#  tasks:
#    - name: Remove Running Base Image
#      docker_container:
#        name: node-ansible-base
#        state: absent
#        force_kill: yes