---
- name: Docker pull node 14.15.0 | add to Ansible Hosts
  hosts: localhost
  tasks:
    - name: Pull node
      docker_container:
        name: "node-ansible-base"
        image: "node:14.15.0-stretch"
        state: started
        ports:
          - "8080:80"
        working_dir: /var/www/
        command: tail -f /dev/null
    - name: Add container with Node to Ansible Hosts
      add_host:
        name: "node-ansible-base"
        ansible_connection: docker
        ansible_ssh_user: root

- name: Configure Node Image for deploy Web server
  hosts: "node-ansible-base"
  gather_facts: false
  tasks:
    - name: Install Rsync
      apt:
        name: rsync
    - name: Install Apache Web Server
      apt:
        name: apache2
    - name: Copy webapp files to docker container
      synchronize:
        src: ./web-app/
        dest: /var/www
    - name: Clean up Rcync
      raw: apt purge rsync -y

- name: Start Apache2 | Yarn install dependenses, build and
  hosts: "node-ansible-base"
  gather_facts: false
  tasks:
    - name: Start Apache
      service:
        name: apache2
        state: started
    - name: Doing Yarn install command
      command: yarn install
    - name: Doing Yarn build command
      command: yarn build
    - name: Move build folder to need path
      copy:
        remote_src: yes
        src: /var/www/build/
        dest: /var/www/html/